### ISSUE TITLE
How to run the webduino-blockly

### ISSUE THREAD

**Issue by hznupeter** [webduinoio/webduino-blockly#4]
I have clone the code.But after I open index.html ,the browser is all black.  I dont know what's wrong with my operations.
And i dont understand the following instruction
Node.js
Require the module first by:

require('webduino-blockly');
Then paste-in the code generated by Blockly.

I really need your help.

**Comment by osk2** [comment]
Hi @hznupeter 

Are you trying to host Webduino Blockly yourself?
If so, make sure you have [Node.js](https://nodejs.org/en/) and [Bower](https://bower.io/#install-bower) installed

Run one command once from below
```
npm install
bower install
npm run start
```

Now, open http://127.0.0.1:8080 in browser, you should see Webduino Blockly loaded.

**Comment by hznupeter** [comment]
yeah, Thank you, Done!
if add the instruction to the README.MD, it will help more people.

**Comment by osk2** [comment]
Nice! We'll update README later.
